name: studyshare
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  cross_file: ^0.3.3+2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^8.0.3
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.4
  firebase_ui_firestore: ^1.6.1
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.11
  flutter_firebase_chat_core: ^1.6.7
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7447
  flutter_speed_dial: ^7.0.0
  flutter_timezone: ^1.0.8
  form_builder_validators: ^9.0.0
  http: ^1.2.0
  icons_plus: ^5.0.0
  intl: ^0.18.1
  mobile_scanner: ^5.1.1
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  shortid: ^0.1.2
  syncfusion_flutter_calendar: ^25.2.4
  timeago: ^3.6.1
  timezone: ^0.9.2
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
