name: studyshare
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^4.15.2
  firebase_ui_firestore: ^1.6.1
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  file_picker: ^6.1.1
  cross_file: ^0.3.3+2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  form_builder_validators: ^9.0.0
  mobile_scanner: ^4.0.0
  syncfusion_flutter_calendar: ^24.2.3
  cupertino_icons: ^1.0.2
  shortid: ^0.1.2
  firebase_storage: ^11.6.4
  flutter_chat_ui: ^1.6.11
  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_types: ^3.6.2
  uuid: ^4.3.3
  url_launcher: ^6.2.4
  http: ^1.2.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
